# Generated by Django 4.1.3 on 2022-11-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('unite', models.CharField(max_length=30)),
                ('valeurMin', models.FloatField()),
                ('valeurMax', models.FloatField()),
            ],
        ),
    ]
