# Generated by Django 4.1.3 on 2022-11-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('datePrise', models.DateTimeField()),
                ('grandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.grandeur')),
            ],
        ),
    ]
